equipment: shoes jacket
    @echo "equipment"

underwear:
    @echo "underwear"

socks: underwear
    @echo "socks"

shirt: underwear
    @echo "shirt"

trousers: shirt
    @echo "trousers"

sweater: shirt
    @echo "sweater"

shoes: trousers
    @echo "shoes"

jacket: sweater
    @echo "jacket"